// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package org.example.protobuf;

public final class MyDataProto {
  private MyDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.MyData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float data = 1;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.Float> getDataList();
    /**
     * <code>repeated float data = 1;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated float data = 1;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    float getData(int index);

    /**
     * <code>int32 bins = 2;</code>
     * @return The bins.
     */
    int getBins();

    /**
     * <code>int32 frames = 3;</code>
     * @return The frames.
     */
    int getFrames();

    /**
     * <code>.protobuf.ExtraObject extra = 4;</code>
     * @return Whether the extra field is set.
     */
    boolean hasExtra();
    /**
     * <code>.protobuf.ExtraObject extra = 4;</code>
     * @return The extra.
     */
    org.example.protobuf.MyDataProto.ExtraObject getExtra();
    /**
     * <code>.protobuf.ExtraObject extra = 4;</code>
     */
    org.example.protobuf.MyDataProto.ExtraObjectOrBuilder getExtraOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.MyData}
   */
  public static final class MyData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.MyData)
      MyDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyData.newBuilder() to construct.
    private MyData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyData() {
      data_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protobuf.MyDataProto.internal_static_protobuf_MyData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protobuf.MyDataProto.internal_static_protobuf_MyData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protobuf.MyDataProto.MyData.class, org.example.protobuf.MyDataProto.MyData.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList data_;
    /**
     * <code>repeated float data = 1;</code>
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated float data = 1;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated float data = 1;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public float getData(int index) {
      return data_.getFloat(index);
    }
    private int dataMemoizedSerializedSize = -1;

    public static final int BINS_FIELD_NUMBER = 2;
    private int bins_ = 0;
    /**
     * <code>int32 bins = 2;</code>
     * @return The bins.
     */
    @java.lang.Override
    public int getBins() {
      return bins_;
    }

    public static final int FRAMES_FIELD_NUMBER = 3;
    private int frames_ = 0;
    /**
     * <code>int32 frames = 3;</code>
     * @return The frames.
     */
    @java.lang.Override
    public int getFrames() {
      return frames_;
    }

    public static final int EXTRA_FIELD_NUMBER = 4;
    private org.example.protobuf.MyDataProto.ExtraObject extra_;
    /**
     * <code>.protobuf.ExtraObject extra = 4;</code>
     * @return Whether the extra field is set.
     */
    @java.lang.Override
    public boolean hasExtra() {
      return extra_ != null;
    }
    /**
     * <code>.protobuf.ExtraObject extra = 4;</code>
     * @return The extra.
     */
    @java.lang.Override
    public org.example.protobuf.MyDataProto.ExtraObject getExtra() {
      return extra_ == null ? org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance() : extra_;
    }
    /**
     * <code>.protobuf.ExtraObject extra = 4;</code>
     */
    @java.lang.Override
    public org.example.protobuf.MyDataProto.ExtraObjectOrBuilder getExtraOrBuilder() {
      return extra_ == null ? org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance() : extra_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeFloatNoTag(data_.getFloat(i));
      }
      if (bins_ != 0) {
        output.writeInt32(2, bins_);
      }
      if (frames_ != 0) {
        output.writeInt32(3, frames_);
      }
      if (extra_ != null) {
        output.writeMessage(4, getExtra());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getDataList().size();
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      if (bins_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bins_);
      }
      if (frames_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, frames_);
      }
      if (extra_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getExtra());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.protobuf.MyDataProto.MyData)) {
        return super.equals(obj);
      }
      org.example.protobuf.MyDataProto.MyData other = (org.example.protobuf.MyDataProto.MyData) obj;

      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (getBins()
          != other.getBins()) return false;
      if (getFrames()
          != other.getFrames()) return false;
      if (hasExtra() != other.hasExtra()) return false;
      if (hasExtra()) {
        if (!getExtra()
            .equals(other.getExtra())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (37 * hash) + BINS_FIELD_NUMBER;
      hash = (53 * hash) + getBins();
      hash = (37 * hash) + FRAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFrames();
      if (hasExtra()) {
        hash = (37 * hash) + EXTRA_FIELD_NUMBER;
        hash = (53 * hash) + getExtra().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.MyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.protobuf.MyDataProto.MyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.protobuf.MyDataProto.MyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.protobuf.MyDataProto.MyData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.MyData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.MyData)
        org.example.protobuf.MyDataProto.MyDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.protobuf.MyDataProto.internal_static_protobuf_MyData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.protobuf.MyDataProto.internal_static_protobuf_MyData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.protobuf.MyDataProto.MyData.class, org.example.protobuf.MyDataProto.MyData.Builder.class);
      }

      // Construct using org.example.protobuf.MyDataProto.MyData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = emptyFloatList();
        bins_ = 0;
        frames_ = 0;
        extra_ = null;
        if (extraBuilder_ != null) {
          extraBuilder_.dispose();
          extraBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.protobuf.MyDataProto.internal_static_protobuf_MyData_descriptor;
      }

      @java.lang.Override
      public org.example.protobuf.MyDataProto.MyData getDefaultInstanceForType() {
        return org.example.protobuf.MyDataProto.MyData.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.protobuf.MyDataProto.MyData build() {
        org.example.protobuf.MyDataProto.MyData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.protobuf.MyDataProto.MyData buildPartial() {
        org.example.protobuf.MyDataProto.MyData result = new org.example.protobuf.MyDataProto.MyData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.example.protobuf.MyDataProto.MyData result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          data_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
      }

      private void buildPartial0(org.example.protobuf.MyDataProto.MyData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bins_ = bins_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.frames_ = frames_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.extra_ = extraBuilder_ == null
              ? extra_
              : extraBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.protobuf.MyDataProto.MyData) {
          return mergeFrom((org.example.protobuf.MyDataProto.MyData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.protobuf.MyDataProto.MyData other) {
        if (other == org.example.protobuf.MyDataProto.MyData.getDefaultInstance()) return this;
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        if (other.getBins() != 0) {
          setBins(other.getBins());
        }
        if (other.getFrames() != 0) {
          setFrames(other.getFrames());
        }
        if (other.hasExtra()) {
          mergeExtra(other.getExtra());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureDataIsMutable();
                data_.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureDataIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  data_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 16: {
                bins_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                frames_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                input.readMessage(
                    getExtraFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList data_ = emptyFloatList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = mutableCopy(data_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated float data = 1;</code>
       * @return A list containing the data.
       */
      public java.util.List<java.lang.Float>
          getDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <code>repeated float data = 1;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated float data = 1;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public float getData(int index) {
        return data_.getFloat(index);
      }
      /**
       * <code>repeated float data = 1;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, float value) {
        
        ensureDataIsMutable();
        data_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 1;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(float value) {
        
        ensureDataIsMutable();
        data_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 1;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int bins_ ;
      /**
       * <code>int32 bins = 2;</code>
       * @return The bins.
       */
      @java.lang.Override
      public int getBins() {
        return bins_;
      }
      /**
       * <code>int32 bins = 2;</code>
       * @param value The bins to set.
       * @return This builder for chaining.
       */
      public Builder setBins(int value) {
        
        bins_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bins = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBins() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bins_ = 0;
        onChanged();
        return this;
      }

      private int frames_ ;
      /**
       * <code>int32 frames = 3;</code>
       * @return The frames.
       */
      @java.lang.Override
      public int getFrames() {
        return frames_;
      }
      /**
       * <code>int32 frames = 3;</code>
       * @param value The frames to set.
       * @return This builder for chaining.
       */
      public Builder setFrames(int value) {
        
        frames_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 frames = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrames() {
        bitField0_ = (bitField0_ & ~0x00000004);
        frames_ = 0;
        onChanged();
        return this;
      }

      private org.example.protobuf.MyDataProto.ExtraObject extra_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.protobuf.MyDataProto.ExtraObject, org.example.protobuf.MyDataProto.ExtraObject.Builder, org.example.protobuf.MyDataProto.ExtraObjectOrBuilder> extraBuilder_;
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       * @return Whether the extra field is set.
       */
      public boolean hasExtra() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       * @return The extra.
       */
      public org.example.protobuf.MyDataProto.ExtraObject getExtra() {
        if (extraBuilder_ == null) {
          return extra_ == null ? org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance() : extra_;
        } else {
          return extraBuilder_.getMessage();
        }
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      public Builder setExtra(org.example.protobuf.MyDataProto.ExtraObject value) {
        if (extraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          extra_ = value;
        } else {
          extraBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      public Builder setExtra(
          org.example.protobuf.MyDataProto.ExtraObject.Builder builderForValue) {
        if (extraBuilder_ == null) {
          extra_ = builderForValue.build();
        } else {
          extraBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      public Builder mergeExtra(org.example.protobuf.MyDataProto.ExtraObject value) {
        if (extraBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            extra_ != null &&
            extra_ != org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance()) {
            getExtraBuilder().mergeFrom(value);
          } else {
            extra_ = value;
          }
        } else {
          extraBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      public Builder clearExtra() {
        bitField0_ = (bitField0_ & ~0x00000008);
        extra_ = null;
        if (extraBuilder_ != null) {
          extraBuilder_.dispose();
          extraBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      public org.example.protobuf.MyDataProto.ExtraObject.Builder getExtraBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getExtraFieldBuilder().getBuilder();
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      public org.example.protobuf.MyDataProto.ExtraObjectOrBuilder getExtraOrBuilder() {
        if (extraBuilder_ != null) {
          return extraBuilder_.getMessageOrBuilder();
        } else {
          return extra_ == null ?
              org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance() : extra_;
        }
      }
      /**
       * <code>.protobuf.ExtraObject extra = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.protobuf.MyDataProto.ExtraObject, org.example.protobuf.MyDataProto.ExtraObject.Builder, org.example.protobuf.MyDataProto.ExtraObjectOrBuilder> 
          getExtraFieldBuilder() {
        if (extraBuilder_ == null) {
          extraBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.example.protobuf.MyDataProto.ExtraObject, org.example.protobuf.MyDataProto.ExtraObject.Builder, org.example.protobuf.MyDataProto.ExtraObjectOrBuilder>(
                  getExtra(),
                  getParentForChildren(),
                  isClean());
          extra_ = null;
        }
        return extraBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.MyData)
    }

    // @@protoc_insertion_point(class_scope:protobuf.MyData)
    private static final org.example.protobuf.MyDataProto.MyData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.protobuf.MyDataProto.MyData();
    }

    public static org.example.protobuf.MyDataProto.MyData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyData>
        PARSER = new com.google.protobuf.AbstractParser<MyData>() {
      @java.lang.Override
      public MyData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MyData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.protobuf.MyDataProto.MyData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExtraObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ExtraObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>int32 data1 = 2;</code>
     * @return The data1.
     */
    int getData1();

    /**
     * <code>int32 data2 = 3;</code>
     * @return The data2.
     */
    int getData2();
  }
  /**
   * Protobuf type {@code protobuf.ExtraObject}
   */
  public static final class ExtraObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.ExtraObject)
      ExtraObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExtraObject.newBuilder() to construct.
    private ExtraObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtraObject() {
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExtraObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protobuf.MyDataProto.internal_static_protobuf_ExtraObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protobuf.MyDataProto.internal_static_protobuf_ExtraObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protobuf.MyDataProto.ExtraObject.class, org.example.protobuf.MyDataProto.ExtraObject.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA1_FIELD_NUMBER = 2;
    private int data1_ = 0;
    /**
     * <code>int32 data1 = 2;</code>
     * @return The data1.
     */
    @java.lang.Override
    public int getData1() {
      return data1_;
    }

    public static final int DATA2_FIELD_NUMBER = 3;
    private int data2_ = 0;
    /**
     * <code>int32 data2 = 3;</code>
     * @return The data2.
     */
    @java.lang.Override
    public int getData2() {
      return data2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (data1_ != 0) {
        output.writeInt32(2, data1_);
      }
      if (data2_ != 0) {
        output.writeInt32(3, data2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (data1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, data1_);
      }
      if (data2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, data2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.protobuf.MyDataProto.ExtraObject)) {
        return super.equals(obj);
      }
      org.example.protobuf.MyDataProto.ExtraObject other = (org.example.protobuf.MyDataProto.ExtraObject) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (getData1()
          != other.getData1()) return false;
      if (getData2()
          != other.getData2()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + DATA1_FIELD_NUMBER;
      hash = (53 * hash) + getData1();
      hash = (37 * hash) + DATA2_FIELD_NUMBER;
      hash = (53 * hash) + getData2();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.protobuf.MyDataProto.ExtraObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.protobuf.MyDataProto.ExtraObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ExtraObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ExtraObject)
        org.example.protobuf.MyDataProto.ExtraObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.protobuf.MyDataProto.internal_static_protobuf_ExtraObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.protobuf.MyDataProto.internal_static_protobuf_ExtraObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.protobuf.MyDataProto.ExtraObject.class, org.example.protobuf.MyDataProto.ExtraObject.Builder.class);
      }

      // Construct using org.example.protobuf.MyDataProto.ExtraObject.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = "";
        data1_ = 0;
        data2_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.protobuf.MyDataProto.internal_static_protobuf_ExtraObject_descriptor;
      }

      @java.lang.Override
      public org.example.protobuf.MyDataProto.ExtraObject getDefaultInstanceForType() {
        return org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.protobuf.MyDataProto.ExtraObject build() {
        org.example.protobuf.MyDataProto.ExtraObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.protobuf.MyDataProto.ExtraObject buildPartial() {
        org.example.protobuf.MyDataProto.ExtraObject result = new org.example.protobuf.MyDataProto.ExtraObject(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.protobuf.MyDataProto.ExtraObject result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data1_ = data1_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.data2_ = data2_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.protobuf.MyDataProto.ExtraObject) {
          return mergeFrom((org.example.protobuf.MyDataProto.ExtraObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.protobuf.MyDataProto.ExtraObject other) {
        if (other == org.example.protobuf.MyDataProto.ExtraObject.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getData1() != 0) {
          setData1(other.getData1());
        }
        if (other.getData2() != 0) {
          setData2(other.getData2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                data1_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                data2_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int data1_ ;
      /**
       * <code>int32 data1 = 2;</code>
       * @return The data1.
       */
      @java.lang.Override
      public int getData1() {
        return data1_;
      }
      /**
       * <code>int32 data1 = 2;</code>
       * @param value The data1 to set.
       * @return This builder for chaining.
       */
      public Builder setData1(int value) {
        
        data1_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 data1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data1_ = 0;
        onChanged();
        return this;
      }

      private int data2_ ;
      /**
       * <code>int32 data2 = 3;</code>
       * @return The data2.
       */
      @java.lang.Override
      public int getData2() {
        return data2_;
      }
      /**
       * <code>int32 data2 = 3;</code>
       * @param value The data2 to set.
       * @return This builder for chaining.
       */
      public Builder setData2(int value) {
        
        data2_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 data2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data2_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.ExtraObject)
    }

    // @@protoc_insertion_point(class_scope:protobuf.ExtraObject)
    private static final org.example.protobuf.MyDataProto.ExtraObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.protobuf.MyDataProto.ExtraObject();
    }

    public static org.example.protobuf.MyDataProto.ExtraObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtraObject>
        PARSER = new com.google.protobuf.AbstractParser<ExtraObject>() {
      @java.lang.Override
      public ExtraObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExtraObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtraObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.protobuf.MyDataProto.ExtraObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MyData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_MyData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ExtraObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ExtraObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\010protobuf\"Z\n\006MyData\022\014\n\004data" +
      "\030\001 \003(\002\022\014\n\004bins\030\002 \001(\005\022\016\n\006frames\030\003 \001(\005\022$\n\005" +
      "extra\030\004 \001(\0132\025.protobuf.ExtraObject\":\n\013Ex" +
      "traObject\022\r\n\005value\030\001 \001(\t\022\r\n\005data1\030\002 \001(\005\022" +
      "\r\n\005data2\030\003 \001(\005B#\n\024org.example.protobufB\013" +
      "MyDataProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_MyData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_MyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_MyData_descriptor,
        new java.lang.String[] { "Data", "Bins", "Frames", "Extra", });
    internal_static_protobuf_ExtraObject_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_ExtraObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ExtraObject_descriptor,
        new java.lang.String[] { "Value", "Data1", "Data2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
